/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/******************************************************************************************************
 *
 * This file contains examples of using GCC-style inline assembly in C for ARM Cortex-M4 targets.
 * It demonstrates how to read/write special registers and how to perform basic memory operations.
 *
 * To run a specific example, set the corresponding `#if` condition to 1.
 *
 *******************************************************************************************************/

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

/*************************************************************************************************************
	  Example 1 :
					Write two inline assembly blocks:

					(a) To read the PRIMASK special register into a C variable.

					(b) To write a value back into PRIMASK
**************************************************************************************************************/

#if 0
	uint32_t premask_val ;
	uint32_t premask_val_change = 1 ;

	__asm volatile ("MRS %0 , PRIMASK" : "=r"(premask_val));

	__asm volatile ("MSR PRIMASK , %0" : : "r"(premask_val_change));

	__asm volatile ("MRS %0 , PRIMASK" : "=r"(premask_val));

#endif


/*************************************************************************************************************
		  Example 2 :
						Write two inline assembly blocks:

						(a) Reads the CONTROL register.

						(b) Sets bit 1 (to switch to Process Stack Pointer).

						(c) Writes the modified value back.

**************************************************************************************************************/

#if 0
	uint32_t control_val ;

	__asm volatile ("MRS %0 , CONTROL" : "=r"(control_val));

	// Modify CONTROL: set bit 1 to switch to PSP (Process Stack Pointer)
	control_val |= (1 << 1);

	__asm volatile ("MSR CONTROL, %0" : : "r"(control_val) );

#endif

/*************************************************************************************************************
			  Example 2 :
							Write two inline assembly blocks:

							(a) Reads the CONTROL register.

							(b) Sets bit 1 (to switch to Process Stack Pointer).

							(c) Writes the modified value back.

**************************************************************************************************************/

#if 0
		uint32_t control_val ;

		__asm volatile ("MRS %0 , CONTROL" : "=r"(control_val));

		// Modify CONTROL: set bit 1 to switch to PSP (Process Stack Pointer)
		control_val |= (1 << 1);

		__asm volatile ("MSR CONTROL, %0" : : "r"(control_val) );

#endif

/*************************************************************************************************************
			Example 3 :
						Write a function using inline assembly that:

						copy the contents of a pointer into another variable
**************************************************************************************************************/

#if 1
		int p1 , *p2 ;
		p2 = (int*)0x20000008;

		__asm volatile ("LDR %0 , [%1]" : "=r"(p1) : "r"(p2));

#endif

	for(;;);
}
